# Gradle
org.gradle.daemon = true
org.gradle.jvmargs = -Xmx3G
org.gradle.parallel = true
org.gradle.caching = true

# Common
java_version = 25
hytale_version = 0.5.4

# Mod options
group = com.mrbysco.gonefishing
manifest_group = com.mrbysco
mod_name = GoneFishing
main_class = com.mrbysco.gonefishing.GoneFishingPlugin
mod_author = Mrbysco,ShyNieke
mod_id = ArmorStand
mod_license = MIT
mod_description = A fishing mod for HyTale
mod_url = https://www.curseforge.com/hytale/mods/gone-fishing
version = 0.5.0
includes_pack = true
disabled_by_default = false
patchline = release
manifestServerVersion = >=0.5.4 <0.6.0
manifest_dependencies = Hytale:EntityModule=*
manifest_opt_dependencies =
curseforgeID = 1421820